import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const dist = resolve("dist");
rmSync(dist, { recursive: true, force: true });
mkdirSync(resolve(dist, ".openai"), { recursive: true });

const html = `<!doctype html><html lang="zh-Hant"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>社團搜尋自動化系統</title><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-slate-50 text-slate-950"><main class="mx-auto grid max-w-7xl gap-6 px-4 py-8"><section class="rounded-[28px] border bg-white p-8 shadow-sm"><p class="font-bold tracking-[.3em] text-blue-700">GROUP FINDER SYSTEM</p><h1 class="mt-3 text-5xl font-black md:text-7xl">社團搜尋自動化系統</h1><p class="mt-5 text-lg text-slate-600">輸入關鍵字和數量，Chrome 擴充功能會開啟 Google 搜尋真正的 Facebook 社團網址。</p><div id="connection" class="mt-5 inline-flex rounded-full bg-amber-50 px-4 py-2 font-bold text-amber-800">● 正在檢查擴充功能…</div></section><section class="rounded-[28px] border bg-white p-6 shadow-sm"><div class="grid gap-3 lg:grid-cols-[1fr_180px_210px_auto]"><textarea id="keyword" rows="2" placeholder="例如：越南房地產、Bất động sản Việt Nam" class="rounded-2xl border px-5 py-4 text-lg"></textarea><input id="count" type="number" min="1" max="1000" value="100" aria-label="搜尋數量" class="rounded-2xl border px-5 text-lg"><button id="search" class="rounded-2xl bg-blue-700 px-7 py-4 text-xl font-black text-white hover:bg-blue-800">🔍 開始搜尋</button><button id="download" disabled class="rounded-2xl bg-violet-700 px-7 py-4 text-lg font-bold text-white disabled:opacity-30">下載 CSV</button></div><p class="mt-3 text-sm text-slate-500">多個關鍵字請用逗號或換行分隔。系統採固定低速模式，每次翻頁間隔 12 秒；失敗會自動退避重試，遇到真人驗證則暫停。</p></section><section class="rounded-[28px] border bg-white p-6 shadow-sm"><div class="flex justify-between gap-4"><div><p class="font-bold tracking-widest text-blue-700">搜尋結果</p><h2 id="title" class="mt-2 text-3xl font-black">尚未搜尋</h2></div><div id="status" class="text-right font-bold text-blue-700">請先確認擴充功能已連線</div></div><div class="mt-5 overflow-auto rounded-2xl border"><table class="w-full min-w-[850px] text-left"><thead class="bg-slate-50"><tr><th class="p-4">排名</th><th class="p-4">社團名稱</th><th class="p-4">網址</th><th class="p-4">搜尋關鍵字</th></tr></thead><tbody id="body"><tr><td colspan="4" class="p-16 text-center text-slate-500">等待搜尋</td></tr></tbody></table></div></section></main><script src="script.js"></script></body></html>`;

const js = `const $=id=>document.getElementById(id);let rows=[];let connected=false;
function ping(){window.postMessage({source:'aiaa-group-finder-page',type:'PING'},'*')}
function render(items){rows=items||[];$('download').disabled=!rows.length;$('body').innerHTML=rows.length?rows.map((r,i)=>'<tr class="border-t"><td class="p-4 font-bold">#'+(i+1)+'</td><td class="p-4">'+escapeHtml(r.title||'Facebook 社團')+'</td><td class="p-4"><a class="break-all text-blue-700 underline" target="_blank" rel="noreferrer" href="'+escapeHtml(r.url)+'">'+escapeHtml(r.url)+'</a></td><td class="p-4">'+escapeHtml(r.keyword||'')+'</td></tr>').join(''):'<tr><td colspan="4" class="p-16 text-center text-slate-500">沒有取得結果</td></tr>'}
function escapeHtml(v){return String(v||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
window.addEventListener('message',e=>{if(e.source!==window||e.data?.source!=='aiaa-group-finder-extension')return;if(e.data.type==='EXTENSION_READY'){connected=true;$('connection').textContent='● Chrome 擴充功能已連線';$('connection').className='mt-5 inline-flex rounded-full bg-emerald-50 px-4 py-2 font-bold text-emerald-700';$('status').textContent='可以開始搜尋'}if(e.data.type==='SEARCH_STATUS')$('status').textContent=e.data.status;if(e.data.type==='SEARCH_BLOCKED'){render(e.data.results||[]);$('title').textContent='Google 真人驗證';$('status').textContent=e.data.status}if(e.data.type==='SEARCH_RESULTS'){render(e.data.results);$('title').textContent='真實 Google 搜尋結果';$('status').textContent='完成，共找到 '+rows.length+' 個社團'}});
$('search').addEventListener('click',()=>{const keywords=$('keyword').value.trim(),count=Math.max(1,Math.min(1000,Number($('count').value)||1));if(!keywords){alert('請輸入關鍵字');return}if(!connected){alert('Chrome 擴充功能尚未連線，請到 chrome://extensions 重新載入擴充功能，再重新整理本頁');ping();return}$('title').textContent='搜尋中…';$('status').textContent='正在交給擴充功能搜尋 Google';render([]);window.postMessage({source:'aiaa-group-finder-page',type:'START_SEARCH',keywords,count},'*')});
$('download').addEventListener('click',()=>{const esc=v=>'\"'+String(v||'').replace(/\"/g,'\"\"')+'\"';const data=[['排名','社團名稱','網址','搜尋關鍵字'],...rows.map((r,i)=>[i+1,r.title,r.url,r.keyword])];const blob=new Blob(['\\ufeff'+data.map(x=>x.map(esc).join(',')).join('\\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='facebook-groups.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
ping();setTimeout(ping,1000);setTimeout(()=>{if(!connected){$('connection').textContent='● 擴充功能未連線';$('connection').className='mt-5 inline-flex rounded-full bg-red-50 px-4 py-2 font-bold text-red-700'}},2200);`;

writeFileSync(resolve(dist, "index.html"), html, "utf8");
writeFileSync(resolve(dist, "script.js"), js, "utf8");
writeFileSync(resolve(dist, ".openai", "hosting.json"), JSON.stringify({ project_id: "appgprj_6a7ea6c042b081919ead78b59f4b29b8" }, null, 2));
